name: run main.py

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chekcout repo content
        uses: actions/checkout@v2 # check out the repository content to github runner

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py